### ISSUE TITLE
Algorithm: artificial intelligence of the enemies

### ISSUE THREAD

**Issue by Koldar** [STB1019/JAM2018#26]
AS a player
I WANT to fight against intelligent enemies
BECAUSE in this way the difficulty level increases

Naive way to implement such algorithm: use A* to generate the path planning of the enemy (the goal state is the one where the enemy is in the same position of the player). If the enemy is near the player, don't use A* but apply the attack action

**Comment by thevinter** [comment]
A basic AI is now working.
