### ISSUE TITLE
Player can perform multiple jump in the air

### ISSUE THREAD

**Issue by Koldar** [STB1019/JAM2018#38]
The player can perform multiple jump in the air.
The check if the jump can be done looks at the moment wether or not the velocity y of the player is 0 ( with a certain threshhold). If this is true, the player can perform the jump.

The problem is that the a player has no velocity y either when is on the ground or when it's at the summit of the parabolic jump trajectory. So, if in that moment he pressed "do Jump" the game allows it.

We need to find a different solution.

See JumpScript

**Comment by thevinter** [comment]
Since the jump check is no longer done using the y velocity this bug is now obsolete.
