### ISSUE TITLE
Avoiding double jump

### ISSUE THREAD

**Issue by Koldar** [STB1019/JAM2018#40]
We have decided to add a tag to every gameobject representing a terrain

**Comment by Koldar** [comment]
I wish to stop the coding because I would like to give this issue to Nikita, if he accepts to work with us of course

**Comment by thevinter** [comment]
With the new script the player can no longer double jump. Closing the issue.

**Comment by Koldar** [comment]
Some code review notes for the task you've just closed:

1. Property names follows PascalCase, not camelCase;
2. why 0.5f is needed in the raycast?
3. Debug.Log("hmmm") is not informative enough. Remove it or change the message content;
4. the script is supposed to be run both by the player and from an artificial intelligence. However, by expliting using `Input.GetKeyDown(KeyCode.S)` the latter option won't be available anymore.  The trick is that JumpScript should provide a method called `RequestJump(GameObject)` where the program will do jump for a particular gameobject. You should not wire this script to the player input;
5. layerMask computation contains a magic number (8). Consider create a class (inside Commons namespace) containing all the used layers inside the project (or an alternative code readable solution)
6. `layerMask = ~layerMask;` `layerMask` keeps being reverse each time a frame is computed. Is this the correct behaviour? I'm not accustomed to the layer management;
7. `jumpForce` should be a parameter of requestJump method;
