### ISSUE TITLE
Creating fountain model

### ISSUE THREAD

**Issue by Koldar** [STB1019/JAM2018#7]
AS A player
I WANT to see a fountain
BECAUSE fountains are love, fountains are life

This task requires you to create the **actual model** for the fountain. After this task is completed, whenever a fountain is to be seen in the maze, the player will see the actual fountain.
You need to have an animation of the water flowing from the fountain as well

**Comment by micheledusi** [comment]
The alpha version of the *fountain* is completed.

I created two different type of fountain model:
- FountainA is animated with a water particle system.
- FountainB is not animated, but it has different layers. Though, water textures does not render as it should, so I suggest not to use it.

Both can be instantiated as prefabs.

Todo list for the future:
(1) Animate the inside water (especially in FountainA).
(2) Create a better material for the waterfall.
(3) Re-texture everything in a better (and more aesthetically pleasing) way.

**Comment by micheledusi** [comment]
Update:
- Water texture is now more realistic (but it still does not move).
- Both fountain versions are now animated and available as prefabs.
